### ISSUE TITLE
touchpad  does not work  after pull code

### ISSUE THREAD

**Issue by wenfer** [bendahl/uinput#35] opened 2023-05-10 12:20 UTC
look like cause  this code
uinput.go
`err = ioctl(deviceFile, uiDevSetup, uintptr(unsafe.Pointer(buf)))`

**Comment by bendahl** [comment] 2023-05-10 19:39
Hi @wenfer,

can you please provide a little more context? Which kernel version are you running this on? Are you using XServer or Wayland? Do you have touchpad support configured in your system? Why are you assuming that the syscall shown above is the cause of this issue?

It would be great to get a little more input. If at all possible, a little code snipped that you're trying to run might help as well. Please let me know, so I can take a look at this.

Cheers,
Ben

**Comment by bendahl** [comment] 2023-05-10 20:03
@wenfer Short update: I did some testing myself and I can certainly reproduce the issue. It looks like you're on to something. Also, reverting the change to the line you mentioned appears to fix it. I will do some further testing to see what exactly is going on here.

**Comment by bendahl** [comment] 2023-05-10 20:24
@wenfer I will revert the change introduced in 1.6.1 that introduced the ioctl. This should fix the issue and keep compatibility with older systems as well.

@gslandtreter Looks like the last change will introduce issues. I don't want to risk breaking compatibility for older systems. Also, taking a closer look at the kernel docs, the current method used by uinput is "the old" way of using uinput, which makes sense, as this library is a couple of years old. I will revert the last change for now and do some investigation on how to ensure that newer systems are able to make use of this library while staying backward compatible (without breaking the API). In the meantime, please use version 1.6.1 to ensure that everything works for you as expected, as it is using the ioctl. Sorry for the inconvenience.

**Comment by bendahl** [comment] 2023-05-10 20:32
Version 1.6.2 fixes this issue. I'm closing it.

**Closed by bendahl** 2023-05-10 20:32 UTC
