### ISSUE TITLE
Missing key codes in inputdefs.go

### ISSUE THREAD

**Issue by messju** [bendahl/uinput#5] opened 2017-06-16 08:49 UTC
Hello,

there is an unclosed comment in inputdefs.go on line 226. I think this is caused by a multiline comment in the original include/linux/input-event-codes.h - this effectively comments out the consts following that line.

Fix ist trivial:
`--       KeySwitchvideomode  = 227 /*CycleBetweenAvailableVideo`
`++       KeySwitchvideomode  = 227 /*CycleBetweenAvailableVideo outputs (Monitor/LCD/TV-out/etc) */`

But nonetheless: Thank you for that great tool, Works like a charm! :-)

**Comment by bendahl** [comment] 2017-06-20 20:10
Hi messju,

I'm glad to hear that you're enjoying the library! 

You are correct. I did accidentally mess up that comment. The issue is fixed in version 0.3.1.
 See: [https://github.com/bendahl/uinput/releases/tag/v0.3.1](url). However, I think that the comments will need a little rework anyway. I will take care of this soon.

Thanks for noticing and helping to improve this library!

Cheers,
Ben

**Closed by bendahl** 2017-06-20 20:10 UTC
